keys:
  - &karsten age1xmna0y66m78sdnaywmq2pndzlpnt9f28l8y7n2un6m7egn092vxszsa2nz
  - &omen15 age1gshjykt0dxdl0hn9rdramfy7vmrautwe4uw6kpmdtp4tv4rz9ckstnrdft
creation_rules:
  - path_regex: secrets/secrets.yaml$
    key_groups:
      - age:
        - *karsten
        - *omen15
