[colors.primary]
background = '#fcf8fa'
foreground = '#1b1b1d'

[colors.selection]
text = '#1b1b1d'
background = '#dee2f2'

[colors.cursor]
text = '#fcf8fa'
cursor = '#595e6c'

[colors.normal]
black   = '#131315'
red     = '#793044'
green   = '#215f2b'
yellow  = '#999326'
blue    = '#5c6171'
magenta = '#b4b7bf'
cyan    = '#595e6c'
white   = '#222223'

[colors.bright]
black   = '#696a6c'
red     = '#a5576c'
green   = '#3f8c4b'
yellow  = '#a5a031'
blue    = '#696f81'
magenta = '#b4b7bf'
cyan    = '#80838c'
white   = '#bbbcbf'
